#!/usr/bin/env python3
"""
Analyze combinatorial test coverage from CSV file generated by Foundry tests.

Usage:
    forge test --match-test testFuzz_CombinatorialExploration --fuzz-runs 100
    python3 analyze_csv_coverage.py coverage_data.csv
"""

import sys
import csv
from collections import Counter

# Enum mappings
PRE_BID_SCENARIOS = {
    0: "NoBidsBeforeUser",
    1: "BidsBeforeUser",
    2: "ClearingPriceBelowMaxPrice",
    3: "BidsAtClearingPrice",
}

POST_BID_SCENARIOS = {
    0: "NoBidsAfterUser",
    1: "UserAboveClearing",
    2: "UserAtClearing",
    3: "UserOutbidLater",
    4: "UserOutbidImmediately",
}

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 analyze_csv_coverage.py coverage_data.csv")
        sys.exit(1)

    filename = sys.argv[1]
    test_cases = []

    # Read CSV file
    with open(filename, 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            if len(row) >= 4:
                test_cases.append({
                    'pre': int(row[0]),
                    'post': int(row[1]),
                    'bid_amount': int(row[2]),
                    'max_price': int(row[3]),
                })

    if not test_cases:
        print("No coverage data found in file.")
        return

    # Analyze coverage
    print(f"\n{'='*80}")
    print(f"  COMBINATORIAL TEST COVERAGE REPORT")
    print(f"{'='*80}\n")
    print(f"Total Test Cases: {len(test_cases)}\n")

    # Scenario coverage
    print(f"{'─'*80}")
    print("SCENARIO COVERAGE")
    print(f"{'─'*80}\n")

    scenario_combos = Counter((tc['pre'], tc['post']) for tc in test_cases)

    print(f"{'Pre Scenario':<35} {'Post Scenario':<35} {'Count':>8}")
    print(f"{'-'*35} {'-'*35} {'-'*8}")
    for (pre, post), count in sorted(scenario_combos.items()):
        pre_name = PRE_BID_SCENARIOS.get(pre, f"Unknown({pre})")
        post_name = POST_BID_SCENARIOS.get(post, f"Unknown({post})")
        print(f"{pre_name:<35} {post_name:<35} {count:>8}")

    # Bid amount statistics
    print(f"\n{'─'*80}")
    print("BID AMOUNT STATISTICS")
    print(f"{'─'*80}\n")

    bid_amounts = [tc['bid_amount'] for tc in test_cases]
    if bid_amounts:
        min_bid = min(bid_amounts)
        max_bid = max(bid_amounts)
        avg_bid = sum(bid_amounts) / len(bid_amounts)

        print(f"Min Bid Amount: {min_bid:>20,} wei ({min_bid / 1e18:.4f} ETH)")
        print(f"Max Bid Amount: {max_bid:>20,} wei ({max_bid / 1e18:.4f} ETH)")
        print(f"Avg Bid Amount: {avg_bid:>20,.0f} wei ({avg_bid / 1e18:.4f} ETH)")

    # Max price statistics
    print(f"\n{'─'*80}")
    print("MAX PRICE STATISTICS (Q96 format)")
    print(f"{'─'*80}\n")

    max_prices = [tc['max_price'] for tc in test_cases]
    if max_prices:
        min_price = min(max_prices)
        max_price = max(max_prices)
        avg_price = sum(max_prices) / len(max_prices)

        print(f"Min Max Price: {min_price:>30,}")
        print(f"Max Max Price: {max_price:>30,}")
        print(f"Avg Max Price: {avg_price:>30,.0f}")

    # Coverage gaps
    print(f"\n{'─'*80}")
    print("COVERAGE GAPS")
    print(f"{'─'*80}\n")

    all_scenarios = set((pre, post) for pre in PRE_BID_SCENARIOS.keys() for post in POST_BID_SCENARIOS.keys())
    tested_scenarios = set(scenario_combos.keys())
    missing_scenarios = all_scenarios - tested_scenarios

    if missing_scenarios:
        print(f"Missing {len(missing_scenarios)}/20 scenario combinations:")
        for pre, post in sorted(missing_scenarios):
            pre_name = PRE_BID_SCENARIOS[pre]
            post_name = POST_BID_SCENARIOS[post]
            print(f"  • {pre_name} + {post_name}")
    else:
        print("✓ All 20 scenario combinations covered!")

    # Distribution analysis
    print(f"\n{'─'*80}")
    print("SCENARIO DISTRIBUTION")
    print(f"{'─'*80}\n")

    pre_distribution = Counter(tc['pre'] for tc in test_cases)
    post_distribution = Counter(tc['post'] for tc in test_cases)

    print("Pre-Bid Scenario Distribution:")
    for pre in sorted(PRE_BID_SCENARIOS.keys()):
        count = pre_distribution.get(pre, 0)
        percentage = (count / len(test_cases) * 100) if test_cases else 0
        name = PRE_BID_SCENARIOS[pre]
        bar = '█' * int(percentage / 2)  # Scale bar to 50 max chars
        print(f"  {name:<35} {count:>5} ({percentage:>5.1f}%) {bar}")

    print("\nPost-Bid Scenario Distribution:")
    for post in sorted(POST_BID_SCENARIOS.keys()):
        count = post_distribution.get(post, 0)
        percentage = (count / len(test_cases) * 100) if test_cases else 0
        name = POST_BID_SCENARIOS[post]
        bar = '█' * int(percentage / 2)
        print(f"  {name:<35} {count:>5} ({percentage:>5.1f}%) {bar}")

    # Heatmap of scenario combinations
    print(f"\n{'─'*80}")
    print("SCENARIO COMBINATION HEATMAP")
    print(f"{'─'*80}\n")

    # Create matrix
    header = "Pre \\ Post"
    print(f"{header:<25}", end="")
    for post in sorted(POST_BID_SCENARIOS.keys()):
        print(f" {POST_BID_SCENARIOS[post][:8]:>8}", end="")
    print()
    print("-" * (25 + 9 * len(POST_BID_SCENARIOS)))

    for pre in sorted(PRE_BID_SCENARIOS.keys()):
        print(f"{PRE_BID_SCENARIOS[pre]:<25}", end="")
        for post in sorted(POST_BID_SCENARIOS.keys()):
            count = scenario_combos.get((pre, post), 0)
            print(f" {count:>8}", end="")
        print()

    print(f"\n{'='*80}\n")

if __name__ == "__main__":
    main()
